name: Build

on:
    pull_request:
        types: [synchronize, opened, reopened]

concurrency:
    group: build
    cancel-in-progress: true

jobs:
    build-and-publish:
        name: Build and Publish
        runs-on: self-hosted-hoprnet-small
        strategy:
            matrix:
                node-version: [20.x, 21.x, 22.x]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: hoprnet/hopr-workflows/actions/setup-node-js@master
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Setup GCP
              id: gcp
              uses: hoprnet/hopr-workflows/actions/setup-gcp@master
              with:
                  google-credentials: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}
                  login-artifact-registry: 'true'

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
              with:
                  driver: kubernetes

            - name: Building
              run: yarn build

            - name: Linting
              run: yarn lint:ci

            - name: Formatting
              run: yarn format:ci

            - name: Testing
              run: yarn test

            - name: Get PR version
              if: matrix.node-version == vars.NODE_VERSION
              id: variables
              run: |
                  PR_VERSION=$(node -p "require('./package.json').version")
                  echo "PR_VERSION=${PR_VERSION}-pr.${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT

            - name: Build and push docker image
              if: matrix.node-version == vars.NODE_VERSION
              uses: docker/build-push-action@v4
              with:
                  push: true
                  tags: ${{ vars.DOCKER_IMAGE_REGISTRY }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ steps.variables.outputs.PR_VERSION }}%
